# Welcome to Jekyll!

# Website settings
title: "Andrea Dal Pozzolo"
description: "Personal website of Andrea Dal Pozzolo"
keywords: "dalpozz,andrea dal pozzolo,machine learning,fraud detection"
baseurl: "/"
url: "http://dalpozz.github.io"




author:
  name: 'Andrea Dal Pozzolo'
  first_name: 'Andrea'
  last_name: 'Dal Pozzolo'
  bio: "I’m passionate about data and I define myself a Data Scientist: I’m an expert in Machine Learning, Data Mining and statistical techniques. In my daily job I use statistical models to extract knowledge from data and provide insights."
  desc: 'I am a data scientist focusing on machine learning for fraud detection.'
  summary: My passion is to turn data into insights and products. Many problems can be solved by asking the right questions and using data to answer them, but many data sources are still untapped. I like working out the questions with the experts and digging down the data to find those gems. Overall, I've more than 6 years of experience in applying statistical and Machine Learning techniques to build prediction models for diverse business and research projects. I've led a team of 3/4 people in several ML projects where we used different Big Data technologies.
  email: 'dalpozz@gmail.com'
  twitter_username: 'dalpozz'
  linkedin_username: 'https://www.linkedin.com/in/dalpozz'
  scholar_username: 'https://scholar.google.ch/citations?user=61wlSEYAAAAJ'
  github_username: 'dalpozz'
  head_img: 'static/img/landing/dalpozz.jpg'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: 'publications'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  # - locale: 'it'
  #   flag: 'static/img/flags/Italy.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-28216313-2

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

